# permissions for end users to view kbkbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kbkb-viewer-role
rules:
- apiGroups:
  - omakenoyouna.net.omakenoyouna.net
  resources:
  - kbkbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - omakenoyouna.net.omakenoyouna.net
  resources:
  - kbkbs/status
  verbs:
  - get
