# permissions for end users to edit kbkbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kbkb-editor-role
rules:
- apiGroups:
  - omakenoyouna.net.omakenoyouna.net
  resources:
  - kbkbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - omakenoyouna.net.omakenoyouna.net
  resources:
  - kbkbs/status
  verbs:
  - get
